#!/bin/bash
gcloud functions deploy poll-webhook-function --region=us-central1 --entry-point=main --runtime=python38 --trigger-topic=poll-webhook-topic --timeout=539 --env-vars-file=/home/nicolas/projects/janium/python/functions/envs.yaml --source=/home/nicolas/projects/janium/python/functions/poll_webhook/ --egress-settings=private-ranges-only --vpc-connector=janium-vpc-connector >> /home/nicolas/projects/janium/python/master_deploy_logs/poll-webhook-function.log 2>&1 &
gcloud functions deploy director-function --region=us-central1 --entry-point=main --runtime=python38 --trigger-topic=janium-main-topic --timeout=539 --env-vars-file=/home/nicolas/projects/janium/python/functions/envs.yaml --source=/home/nicolas/projects/janium/python/functions/director/ --egress-settings=private-ranges-only --vpc-connector=janium-vpc-connector >> /home/nicolas/projects/janium/python/master_deploy_logs/director-function.log 2>&1 &
gcloud functions deploy send-email-function --region=us-central1 --entry-point=main --runtime=python38 --trigger-topic=send-email-topic --timeout=539 --env-vars-file=/home/nicolas/projects/janium/python/functions/envs.yaml --source=/home/nicolas/projects/janium/python/functions/send_email/ --egress-settings=private-ranges-only --vpc-connector=janium-vpc-connector >> /home/nicolas/projects/janium/python/master_deploy_logs/send-email-function.log 2>&1 &
gcloud functions deploy track-email-open-function --region=us-central1 --entry-point=main --runtime=python38 --trigger-http --timeout=539 --env-vars-file=/home/nicolas/projects/janium/python/functions/envs.yaml --source=/home/nicolas/projects/janium/python/functions/track_email_open/ --allow-unauthenticated --egress-settings=private-ranges-only --vpc-connector=janium-vpc-connector >> /home/nicolas/projects/janium/python/master_deploy_logs/track-email-open-function.log 2>&1 &gcloud functions deploy send-daily-tasks-function --region=us-central1 --entry-point=main --runtime=python38 --trigger-topic=send-daily-tasks-topic --timeout=539 --env-vars-file=/home/nicolas/projects/janium/python/functions/envs.yaml --source=/home/nicolas/projects/janium/python/functions/send_daily_tasks/ --egress-settings=private-ranges-only --vpc-connector=janium-vpc-connector >> /home/nicolas/projects/janium/python/master_deploy_logs/send-daily-tasks-function.log 2>&1 &
gcloud functions deploy send-test-email-function --region=us-central1 --entry-point=main --runtime=python38 --trigger-http --timeout=539 --source=/home/nicolas/projects/janium/python/functions/send_test_email/ >> /home/nicolas/projects/janium/python/master_deploy_logs/send-test-email-function.log 2>&1 &
gcloud functions deploy send-daily-tasks-function --region=us-central1 --entry-point=main --runtime=python38 --trigger-topic=send-daily-tasks-topic --timeout=539 --env-vars-file=/home/nicolas/projects/janium/python/functions/envs.yaml --source=/home/nicolas/projects/janium/python/functions/send_daily_tasks/ --egress-settings=private-ranges-only --vpc-connector=janium-vpc-connector >> /home/nicolas/projects/janium/python/master_deploy_logs/send-daily-tasks-function.log 2>&1 &
gcloud functions deploy get-ulinc-campaigns-function --region=us-central1 --entry-point=main --runtime=python38 --trigger-http --allow-unauthenticated --timeout=539 --source=/home/nicolas/projects/janium/python/functions/get_ulinc_campaigns/ --env-vars-file=/home/nicolas/projects/janium/python/functions/envs.yaml --egress-settings=private-ranges-only --vpc-connector=janium-vpc-connector >> /home/nicolas/projects/janium/python/master_deploy_logs/get_ulinc_campaigns.log 2>&1 &
gcloud functions deploy get-ulinc-client-info-function --region=us-central1 --entry-point=main --runtime=python38 --trigger-http --allow-unauthenticated --timeout=539 --source=/home/nicolas/projects/janium/python/functions/get_ulinc_client_info// >> /home/nicolas/projects/janium/python/master_deploy_logs/get_ulinc_client_info.log 2>&1 &
gcloud functions deploy email-opt-out-function --region=us-central1 --entry-point=main --runtime=python38 --trigger-http --timeout=539 --env-vars-file=/home/nicolas/projects/janium/python/functions/envs.yaml --source=/home/nicolas/projects/janium/python/functions/email_opt_out/ --allow-unauthenticated --egress-settings=private-ranges-only --vpc-connector=janium-vpc-connector >> /home/nicolas/projects/janium/python/master_deploy_logs/email-opt-out-function.log 2>&1 &
gcloud functions deploy dte-profile-redirect-function --region=us-central1 --entry-point=main --runtime=python38 --trigger-http --timeout=539 --env-vars-file=/home/nicolas/projects/janium/python/functions/envs.yaml --source=/home/nicolas/projects/janium/python/functions/dte_profile_redirect/ --allow-unauthenticated --egress-settings=private-ranges-only --vpc-connector=janium-vpc-connector >> /home/nicolas/projects/janium/python/master_deploy_logs/dte-profile-redirect-function.log 2>&1 &
gcloud functions deploy mark-no-interest-function --region=us-central1 --entry-point=main --runtime=python38 --trigger-topic=mark-no-interest-topic --timeout=539 --env-vars-file=/home/nicolas/projects/janium/python/functions/envs.yaml --source=/home/nicolas/projects/janium/python/functions/mark_no_interest/ --egress-settings=private-ranges-only --vpc-connector=janium-vpc-connector >> /home/nicolas/projects/janium/python/master_deploy_logs/mark-no-interest-function.log 2>&1 &
gcloud functions deploy refresh-ulinc-campaigns-function --region=us-central1 --entry-point=main --runtime=python38 --trigger-topic=refresh-ulinc-campaigns-topic --timeout=539 --source=/home/nicolas/projects/janium/python/functions/refresh_ulinc_campaigns/ --env-vars-file=/home/nicolas/projects/janium/python/functions/envs.yaml --egress-settings=private-ranges-only --vpc-connector=janium-vpc-connector >> /home/nicolas/projects/janium/python/master_deploy_logs/refresh_ulinc_campaigns.log 2>&1 &
gcloud functions deploy send-email-with-sendgrid-function --region=us-central1 --entry-point=main --runtime=python38 --trigger-topic=send-email-with-sendgrid-topic --timeout=539 --env-vars-file=/home/nicolas/projects/janium/python/functions/envs.yaml --source=/home/nicolas/projects/janium/python/functions/send_email_with_sendgrid/ --egress-settings=private-ranges-only --vpc-connector=janium-vpc-connector >> /home/nicolas/projects/janium/python/master_deploy_logs/send-email-with-sendgrid-function.log 2>&1 &
gcloud functions deploy update-email-sends-function --memory=1024MB --region=us-central1 --entry-point=main --runtime=python38 --trigger-topic=update-email-sends-topic --timeout=539 --env-vars-file=/home/nicolas/projects/janium/python/functions/envs.yaml --source=/home/nicolas/projects/janium/python/functions/update_email_sends/ --egress-settings=private-ranges-only --vpc-connector=janium-vpc-connector >> /home/nicolas/projects/janium/python/master_deploy_logs/update-email-sends-function.log 2>&1 &
gcloud functions deploy send-li-message-function --region=us-central1 --entry-point=main --runtime=python38 --trigger-topic=send-li-message-topic --timeout=539 --env-vars-file=/home/nicolas/projects/janium/python/functions/envs.yaml --source=/home/nicolas/projects/janium/python/functions/send_li_message/ --egress-settings=private-ranges-only --vpc-connector=janium-vpc-connector >> /home/nicolas/projects/janium/python/master_deploy_logs/send-li-message-function.log 2>&1 &
gcloud functions deploy refresh-ulinc-cookies-function --region=us-central1 --entry-point=main --runtime=python38 --trigger-topic=refresh-ulinc-cookies-topic --timeout=539 --source=/home/nicolas/projects/janium/python/functions/refresh_ulinc_cookies/ --env-vars-file=/home/nicolas/projects/janium/python/functions/envs.yaml --egress-settings=private-ranges-only --vpc-connector=janium-vpc-connector >> /home/nicolas/projects/janium/python/master_deploy_logs/refresh_ulinc_cookies.log 2>&1 &
gcloud functions deploy sendgrid-inbound-parse-function --region=us-central1 --entry-point=main --runtime=python38 --trigger-http --timeout=539 --env-vars-file=/home/nicolas/projects/janium/python/functions/envs.yaml --source=/home/nicolas/projects/janium/python/functions/sendgrid_inbound_parse/ --egress-settings=private-ranges-only --vpc-connector=janium-vpc-connector >> /home/nicolas/projects/janium/python/master_deploy_logs/sendgrid-inbound-parse-function.log 2>&1 &

exec bash