steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['fetch', '--unshallow']
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args: ['ls', '-la']
# - name: 'gcr.io/cloud-builders/git'
#   args: ['branch']


# - name: 'gcr.io/cloud-builders/gcloud'
#   entrypoint: 'bash'
#   args: ['./janium_deploy.sh']
