"""add is_email_forward and tib_id columns

Revision ID: 484dfe1add1c
Revises: 96e046678200
Create Date: 2021-02-17 16:00:25.357351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484dfe1add1c'
down_revision = '96e046678200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('is_email_forward', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('contact', sa.Column('tib_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'tib_id')
    op.drop_column('client', 'is_email_forward')
    # ### end Alembic commands ###
