"""add to_email_addr to Action table

Revision ID: 4fd45561bf99
Revises: 2cdb0091b73f
Create Date: 2021-03-22 09:59:24.623053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fd45561bf99'
down_revision = '2cdb0091b73f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action', sa.Column('to_email_addr', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action', 'to_email_addr')
    # ### end Alembic commands ###
