"""added all tables

Revision ID: 655152f9f82c
Revises: 68b2a6d0f1a3
Create Date: 2021-02-04 13:02:16.316624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '655152f9f82c'
down_revision = '68b2a6d0f1a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('date_added', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_updated', sa.DateTime(), server_default=sa.text('NOW() ON UPDATE NOW()'), nullable=True),
    sa.Column('action_timestamp', sa.DateTime(), nullable=True),
    sa.Column('action_id', sa.String(length=36), nullable=False),
    sa.Column('action_message', sa.Text(), nullable=True),
    sa.Column('is_ulinc_messenger_origin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ulinc_messenger_campaign_id', sa.String(length=10), nullable=True),
    sa.Column('backdated_connection_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['action_name.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action')
    # ### end Alembic commands ###
