"""add is_data_enrichment flag to client

Revision ID: 8a46e3cf013c
Revises: 1fa114ff98a9
Create Date: 2021-03-05 13:11:05.561894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a46e3cf013c'
down_revision = '1fa114ff98a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('is_data_enrichment', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'is_data_enrichment')
    # ### end Alembic commands ###
