"""add voicemail_task_delay to client

Revision ID: 96e046678200
Revises: d43942ab3b74
Create Date: 2021-02-15 13:45:48.368426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96e046678200'
down_revision = 'd43942ab3b74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('voicemail_task_delay', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'voicemail_task_delay')
    # ### end Alembic commands ###
