"""add scrubbed firstname, company and location fields to contact table

Revision ID: b6f613d8be61
Revises: 591315dc14f4
Create Date: 2021-03-04 14:18:52.567642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f613d8be61'
down_revision = '591315dc14f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('scrubbed_company', sa.String(length=250), nullable=True))
    op.add_column('contact', sa.Column('scrubbed_first_name', sa.String(length=100), nullable=True))
    op.add_column('contact', sa.Column('scrubbed_location', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'scrubbed_location')
    op.drop_column('contact', 'scrubbed_first_name')
    op.drop_column('contact', 'scrubbed_company')
    # ### end Alembic commands ###
