"""first revision

Revision ID: d43942ab3b74
Revises: 
Create Date: 2021-02-10 11:38:55.972910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd43942ab3b74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_type',
    sa.Column('action_type_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('action_type_description', sa.String(length=512), nullable=False),
    sa.Column('asOfStartTime', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('asOfEndTime', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('effective_start_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('effective_end_date', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('updatedBy', sa.String(length=36), server_default=sa.text("'45279d74-b359-49cd-bb94-d75e06ae64bc'"), nullable=True),
    sa.PrimaryKeyConstraint('action_type_id')
    )
    op.create_table('client_group_manager',
    sa.Column('client_group_manager_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=256), sa.Computed("CONCAT(first_name, ' ', last_name)", ), nullable=True),
    sa.Column('asOfStartTime', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('asOfEndTime', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('effective_start_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('effective_end_date', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('updatedBy', sa.String(length=36), server_default=sa.text("'45279d74-b359-49cd-bb94-d75e06ae64bc'"), nullable=True),
    sa.PrimaryKeyConstraint('client_group_manager_id')
    )
    op.create_table('cookie_type',
    sa.Column('cookie_type_id', sa.Integer(), nullable=False),
    sa.Column('cookie_type', sa.String(length=64), nullable=False),
    sa.Column('cookie_type_description', sa.String(length=512), nullable=True),
    sa.Column('cookie_type_website_url', sa.String(length=1024), nullable=True),
    sa.Column('asOfStartTime', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('asOfEndTime', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('effective_start_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('effective_end_date', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('updatedBy', sa.String(length=36), server_default=sa.text("'45279d74-b359-49cd-bb94-d75e06ae64bc'"), nullable=True),
    sa.PrimaryKeyConstraint('cookie_type_id')
    )
    op.create_table('credentials',
    sa.Column('credentials_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('asOfStartTime', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('asOfEndTime', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('effective_start_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('effective_end_date', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('updatedBy', sa.String(length=36), server_default=sa.text("'45279d74-b359-49cd-bb94-d75e06ae64bc'"), nullable=True),
    sa.PrimaryKeyConstraint('credentials_id')
    )
    op.create_table('dte',
    sa.Column('dte_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('subject', sa.String(length=1000), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('asOfStartTime', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('asOfEndTime', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('effective_start_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('effective_end_date', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('updatedBy', sa.String(length=36), server_default=sa.text("'45279d74-b359-49cd-bb94-d75e06ae64bc'"), nullable=True),
    sa.PrimaryKeyConstraint('dte_id')
    )
    op.create_table('email_server',
    sa.Column('email_server_id', sa.String(length=36), nullable=False),
    sa.Column('email_server_name', sa.String(length=64), nullable=False),
    sa.Column('smtp_address', sa.String(length=64), nullable=False),
    sa.Column('smtp_tls_port', sa.Integer(), nullable=False),
    sa.Column('smtp_ssl_port', sa.Integer(), nullable=False),
    sa.Column('imap_address', sa.String(length=64), nullable=False),
    sa.Column('imap_ssl_port', sa.Integer(), nullable=False),
    sa.Column('asOfStartTime', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('asOfEndTime', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('effective_start_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('effective_end_date', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('updatedBy', sa.String(length=36), server_default=sa.text("'45279d74-b359-49cd-bb94-d75e06ae64bc'"), nullable=True),
    sa.PrimaryKeyConstraint('email_server_id')
    )
    op.create_table('janium_campaign_step_type',
    sa.Column('janium_campaign_step_type_id', sa.Integer(), nullable=False),
    sa.Column('janium_campaign_step_type', sa.String(length=64), nullable=False),
    sa.Column('janium_campaign_step_type_description', sa.String(length=512), nullable=False),
    sa.Column('asOfStartTime', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('asOfEndTime', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('effective_start_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('effective_end_date', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('updatedBy', sa.String(length=36), server_default=sa.text("'45279d74-b359-49cd-bb94-d75e06ae64bc'"), nullable=True),
    sa.PrimaryKeyConstraint('janium_campaign_step_type_id')
    )
    op.create_table('webhook_response_type',
    sa.Column('webhook_response_type_id', sa.Integer(), nullable=False),
    sa.Column('webhook_response_type', sa.String(length=64), nullable=False),
    sa.Column('webhook_response_type_description', sa.String(length=512), nullable=False),
    sa.Column('asOfStartTime', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('asOfEndTime', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('effective_start_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('effective_end_date', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('updatedBy', sa.String(length=36), server_default=sa.text("'45279d74-b359-49cd-bb94-d75e06ae64bc'"), nullable=True),
    sa.PrimaryKeyConstraint('webhook_response_type_id')
    )
    op.create_table('cookie',
    sa.Column('cookie_id', sa.String(length=36), nullable=False),
    sa.Column('cookie_type_id', sa.Integer(), nullable=True),
    sa.Column('cookie_json_value', sa.JSON(), nullable=False),
    sa.Column('asOfStartTime', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('asOfEndTime', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('effective_start_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('effective_end_date', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('updatedBy', sa.String(length=36), server_default=sa.text("'45279d74-b359-49cd-bb94-d75e06ae64bc'"), nullable=True),
    sa.ForeignKeyConstraint(['cookie_type_id'], ['cookie_type.cookie_type_id'], ),
    sa.PrimaryKeyConstraint('cookie_id')
    )
    op.create_table('email_config',
    sa.Column('email_config_id', sa.String(length=36), nullable=False),
    sa.Column('credentials_id', sa.String(length=36), nullable=True),
    sa.Column('email_server_id', sa.String(length=36), nullable=True),
    sa.Column('is_sendgrid', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sendgrid_sender_id', sa.String(length=36), nullable=True),
    sa.Column('asOfStartTime', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('asOfEndTime', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('effective_start_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('effective_end_date', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('updatedBy', sa.String(length=36), server_default=sa.text("'45279d74-b359-49cd-bb94-d75e06ae64bc'"), nullable=True),
    sa.ForeignKeyConstraint(['credentials_id'], ['credentials.credentials_id'], ),
    sa.ForeignKeyConstraint(['email_server_id'], ['email_server.email_server_id'], ),
    sa.PrimaryKeyConstraint('email_config_id')
    )
    op.create_table('dte_sender',
    sa.Column('dte_sender_id', sa.String(length=36), nullable=False),
    sa.Column('email_config_id', sa.String(length=36), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), sa.Computed("CONCAT(first_name, ' ', last_name)", ), nullable=True),
    sa.Column('asOfStartTime', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('asOfEndTime', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('effective_start_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('effective_end_date', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('updatedBy', sa.String(length=36), server_default=sa.text("'45279d74-b359-49cd-bb94-d75e06ae64bc'"), nullable=True),
    sa.ForeignKeyConstraint(['email_config_id'], ['email_config.email_config_id'], ),
    sa.PrimaryKeyConstraint('dte_sender_id')
    )
    op.create_table('ulinc_config',
    sa.Column('ulinc_config_id', sa.String(length=36), nullable=False),
    sa.Column('credentials_id', sa.String(length=36), nullable=True),
    sa.Column('cookie_id', sa.String(length=36), nullable=True),
    sa.Column('client_ulinc_id', sa.String(length=16), nullable=False),
    sa.Column('new_connection_webhook', sa.String(length=256), nullable=False),
    sa.Column('new_message_webhook', sa.String(length=256), nullable=False),
    sa.Column('send_message_webhook', sa.String(length=256), nullable=False),
    sa.Column('asOfStartTime', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('asOfEndTime', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('effective_start_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('effective_end_date', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('updatedBy', sa.String(length=36), server_default=sa.text("'45279d74-b359-49cd-bb94-d75e06ae64bc'"), nullable=True),
    sa.ForeignKeyConstraint(['cookie_id'], ['cookie.cookie_id'], ),
    sa.ForeignKeyConstraint(['credentials_id'], ['credentials.credentials_id'], ),
    sa.PrimaryKeyConstraint('ulinc_config_id')
    )
    op.create_table('client_group',
    sa.Column('client_group_id', sa.String(length=36), nullable=False),
    sa.Column('client_group_manager_id', sa.String(length=36), nullable=True),
    sa.Column('dte_id', sa.String(length=36), nullable=True),
    sa.Column('dte_sender_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('asOfStartTime', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('asOfEndTime', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('effective_start_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('effective_end_date', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('updatedBy', sa.String(length=36), server_default=sa.text("'45279d74-b359-49cd-bb94-d75e06ae64bc'"), nullable=True),
    sa.ForeignKeyConstraint(['client_group_manager_id'], ['client_group_manager.client_group_manager_id'], ),
    sa.ForeignKeyConstraint(['dte_id'], ['dte.dte_id'], ),
    sa.ForeignKeyConstraint(['dte_sender_id'], ['dte_sender.dte_sender_id'], ),
    sa.PrimaryKeyConstraint('client_group_id')
    )
    op.create_table('client',
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('client_group_id', sa.String(length=36), nullable=True),
    sa.Column('ulinc_config_id', sa.String(length=36), nullable=True),
    sa.Column('email_config_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_sending_emails', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_sending_li_messages', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_dte', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_assistant', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('first_name', sa.String(length=126), nullable=False),
    sa.Column('last_name', sa.String(length=126), nullable=False),
    sa.Column('full_name', sa.String(length=256), sa.Computed("CONCAT(first_name, ' ', last_name)", ), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('company', sa.String(length=256), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('primary_email', sa.String(length=256), nullable=False),
    sa.Column('campaign_management_email', sa.String(length=256), nullable=True),
    sa.Column('alternate_dte_email', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=256), nullable=True),
    sa.Column('assistant_first_name', sa.String(length=128), nullable=True),
    sa.Column('assistant_last_name', sa.String(length=128), nullable=True),
    sa.Column('assistant_full_name', sa.String(length=256), sa.Computed("CONCAT(assistant_first_name, ' ', assistant_last_name)", ), nullable=True),
    sa.Column('assistant_email', sa.String(length=256), nullable=True),
    sa.Column('asOfStartTime', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('asOfEndTime', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('effective_start_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('effective_end_date', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('updatedBy', sa.String(length=36), server_default=sa.text("'45279d74-b359-49cd-bb94-d75e06ae64bc'"), nullable=True),
    sa.ForeignKeyConstraint(['client_group_id'], ['client_group.client_group_id'], ),
    sa.ForeignKeyConstraint(['email_config_id'], ['email_config.email_config_id'], ),
    sa.ForeignKeyConstraint(['ulinc_config_id'], ['ulinc_config.ulinc_config_id'], ),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('janium_campaign',
    sa.Column('janium_campaign_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('email_config_id', sa.String(length=36), nullable=True),
    sa.Column('janium_campaign_name', sa.String(length=512), nullable=False),
    sa.Column('janium_campaign_description', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_messenger', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('asOfStartTime', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('asOfEndTime', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('effective_start_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('effective_end_date', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('updatedBy', sa.String(length=36), server_default=sa.text("'45279d74-b359-49cd-bb94-d75e06ae64bc'"), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], ),
    sa.ForeignKeyConstraint(['email_config_id'], ['email_config.email_config_id'], ),
    sa.PrimaryKeyConstraint('janium_campaign_id')
    )
    op.create_table('webhook_response',
    sa.Column('webhook_response_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('webhook_response_type_id', sa.Integer(), nullable=True),
    sa.Column('webhook_response_value', sa.JSON(), nullable=False),
    sa.Column('asOfStartTime', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('asOfEndTime', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('effective_start_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('effective_end_date', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('updatedBy', sa.String(length=36), server_default=sa.text("'45279d74-b359-49cd-bb94-d75e06ae64bc'"), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], ),
    sa.ForeignKeyConstraint(['webhook_response_type_id'], ['webhook_response_type.webhook_response_type_id'], ),
    sa.PrimaryKeyConstraint('webhook_response_id')
    )
    op.create_table('janium_campaign_step',
    sa.Column('janium_campaign_step_id', sa.String(length=36), nullable=False),
    sa.Column('janium_campaign_id', sa.String(length=36), nullable=False),
    sa.Column('janium_campaign_step_type_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('janium_campaign_step_delay', sa.Integer(), nullable=False),
    sa.Column('janium_campaign_step_body', sa.Text(), nullable=True),
    sa.Column('janium_campaign_step_subject', sa.String(length=1000), nullable=True),
    sa.Column('asOfStartTime', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('asOfEndTime', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('effective_start_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('effective_end_date', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('updatedBy', sa.String(length=36), server_default=sa.text("'45279d74-b359-49cd-bb94-d75e06ae64bc'"), nullable=True),
    sa.ForeignKeyConstraint(['janium_campaign_id'], ['janium_campaign.janium_campaign_id'], ),
    sa.ForeignKeyConstraint(['janium_campaign_step_type_id'], ['janium_campaign_step_type.janium_campaign_step_type_id'], ),
    sa.PrimaryKeyConstraint('janium_campaign_step_id')
    )
    op.create_table('ulinc_campaign',
    sa.Column('ulinc_campaign_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('janium_campaign_id', sa.String(length=36), nullable=True),
    sa.Column('ulinc_campaign_name', sa.String(length=512), nullable=False),
    sa.Column('ulinc_is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ulinc_ulinc_campaign_id', sa.String(length=20), nullable=False),
    sa.Column('ulinc_is_messenger', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('asOfStartTime', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('asOfEndTime', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('effective_start_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('effective_end_date', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('updatedBy', sa.String(length=36), server_default=sa.text("'45279d74-b359-49cd-bb94-d75e06ae64bc'"), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], ),
    sa.ForeignKeyConstraint(['janium_campaign_id'], ['janium_campaign.janium_campaign_id'], ),
    sa.PrimaryKeyConstraint('ulinc_campaign_id')
    )
    op.create_table('contact',
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('janium_campaign_id', sa.String(length=36), nullable=False),
    sa.Column('ulinc_campaign_id', sa.String(length=36), nullable=False),
    sa.Column('webhook_response_id', sa.String(length=36), nullable=False),
    sa.Column('ulinc_id', sa.String(length=20), nullable=False),
    sa.Column('ulinc_ulinc_campaign_id', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), sa.Computed("CONCAT(first_name, ' ', last_name)", ), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('company', sa.String(length=250), nullable=True),
    sa.Column('location', sa.String(length=250), nullable=True),
    sa.Column('email1', sa.String(length=250), nullable=True),
    sa.Column('email2', sa.String(length=250), nullable=True),
    sa.Column('email3', sa.String(length=250), nullable=True),
    sa.Column('phone', sa.String(length=250), nullable=True),
    sa.Column('website', sa.String(length=250), nullable=True),
    sa.Column('li_profile_url', sa.String(length=500), nullable=True),
    sa.Column('asOfStartTime', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('asOfEndTime', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('effective_start_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('effective_end_date', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('updatedBy', sa.String(length=36), server_default=sa.text("'45279d74-b359-49cd-bb94-d75e06ae64bc'"), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], ),
    sa.ForeignKeyConstraint(['janium_campaign_id'], ['janium_campaign.janium_campaign_id'], ),
    sa.ForeignKeyConstraint(['ulinc_campaign_id'], ['ulinc_campaign.ulinc_campaign_id'], ),
    sa.ForeignKeyConstraint(['webhook_response_id'], ['webhook_response.webhook_response_id'], ),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.create_table('action',
    sa.Column('action_id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('action_type_id', sa.Integer(), nullable=False),
    sa.Column('action_timestamp', sa.DateTime(), nullable=True),
    sa.Column('action_message', sa.Text(), nullable=True),
    sa.Column('asOfStartTime', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('asOfEndTime', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('effective_start_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('effective_end_date', sa.DateTime(), server_default=sa.text("'9999-12-31 10:10:10'"), nullable=True),
    sa.Column('updatedBy', sa.String(length=36), server_default=sa.text("'45279d74-b359-49cd-bb94-d75e06ae64bc'"), nullable=True),
    sa.ForeignKeyConstraint(['action_type_id'], ['action_type.action_type_id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.contact_id'], ),
    sa.PrimaryKeyConstraint('action_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action')
    op.drop_table('contact')
    op.drop_table('ulinc_campaign')
    op.drop_table('janium_campaign_step')
    op.drop_table('webhook_response')
    op.drop_table('janium_campaign')
    op.drop_table('client')
    op.drop_table('client_group')
    op.drop_table('ulinc_config')
    op.drop_table('dte_sender')
    op.drop_table('email_config')
    op.drop_table('cookie')
    op.drop_table('webhook_response_type')
    op.drop_table('janium_campaign_step_type')
    op.drop_table('email_server')
    op.drop_table('dte')
    op.drop_table('credentials')
    op.drop_table('cookie_type')
    op.drop_table('client_group_manager')
    op.drop_table('action_type')
    # ### end Alembic commands ###
