steps:
  - id: "deploy function-error-notifier-function"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['-c', 'gcloud functions deploy function-error-notifier-function --runtime=python38 --timeout=180 --region=us-central1 --trigger-topic=janium-logging-topic --source=./janium_functions/function_error_notifier/ --entry-point=main --egress-settings=private-ranges-only --vpc-connector=prod-vpc-connector --set-env-vars=PROJECT_ID=foundation-production,DB_USER=gcf,DB_PASSWORD=$$DB_PASSWORD_SECRET,DB_PRIVATE_HOST=$$DB_PRIVATE_HOST_SECRET,DB_DATABASE=prod,SENDGRID_API_KEY=$$SENDGRID_API_KEY_SECRET']
    secretEnv: ['DB_PASSWORD_SECRET', 'DB_PRIVATE_HOST_SECRET', 'SENDGRID_API_KEY_SECRET']

availableSecrets:
  secretManager:
  - versionName: projects/foundation-production/secrets/prod_db_password/versions/latest
    env: 'DB_PASSWORD_SECRET'
  - versionName: projects/foundation-production/secrets/prod_db_private_host/versions/latest
    env: 'DB_PRIVATE_HOST_SECRET'
  - versionName: projects/foundation-production/secrets/sendgrid-api-key/versions/latest
    env: 'SENDGRID_API_KEY_SECRET'