steps:
  - id: "deploy data-enrichment-function"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['-c', 'gcloud functions deploy data-enrichment-function --runtime=python38 --timeout=180 --region=us-central1 --trigger-topic=janium-data-enrichment-topic --source=./janium_functions/data_enrichment/data_enrichment_function --entry-point=main --egress-settings=private-ranges-only --vpc-connector=staging-vpc-connector --set-env-vars=PROJECT_ID=foundation-staging-305217,DB_USER=gcf,DB_PASSWORD=$$DB_PASSWORD_SECRET,DB_PRIVATE_HOST=$$DB_PRIVATE_HOST_SECRET,DB_DATABASE=staging']
    secretEnv: ['DB_PASSWORD_SECRET', 'DB_PRIVATE_HOST_SECRET']

  - id: "deploy data-enrichment-director-function"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['-c', 'gcloud functions deploy data-enrichment-director-function --runtime=python38 --timeout=180 --region=us-central1 --trigger-topic=janium-data-enrichment-director-topic --source=./janium_functions/data_enrichment/data_enrichment_director --entry-point=main --egress-settings=private-ranges-only --vpc-connector=staging-vpc-connector --set-env-vars=PROJECT_ID=foundation-staging-305217,DB_USER=gcf,DB_PASSWORD=$$DB_PASSWORD_SECRET,DB_PRIVATE_HOST=$$DB_PRIVATE_HOST_SECRET,DB_DATABASE=staging']
    secretEnv: ['DB_PASSWORD_SECRET', 'DB_PRIVATE_HOST_SECRET']

availableSecrets:
  secretManager:
  - versionName: projects/foundation-staging-305217/secrets/staging_db_password/versions/latest
    env: 'DB_PASSWORD_SECRET'
  - versionName: projects/foundation-staging-305217/secrets/staging_db_private_host/versions/latest
    env: 'DB_PRIVATE_HOST_SECRET'